<?php

/**
 * Implements hook_init().
 */
function user_profile_init() {
  global $user;
  $account = user_load($user->uid);
  
}

/**
 * Implements hook_menu().
 */
function user_profile_menu(){
	$items = array();
	$items['user-profile'] = array(
		'page callback' 	=> 'drupal_get_form',
		'page arguments' 	=> array('user_profile'), 
		'access arguments' 	=> array('administer user profile'),
		'file'				=> 'user_profile.admin.inc',	
	);
	
	$items['home'] = array(
		'page callback' 	=> 'user_home',		
		'access arguments' 	=> array('administer user profile'),
		'file'				=> 'user_profile.admin.inc',	
	);
	return $items;
}

/**
 * Implements hook_permission().
 */
function user_profile_permission() {
  return array(
    'administer user profile' => array(
      'title' => t('user profile'),
      'description' => t('Only authenticated user can access this pages.'),
    ),
  );
}


/**
 * Implements hook_user_insert().
 */
function user_profile_user_insert(&$edit, $account, $category) {
	db_insert('user_profile_master')
		->fields(array(
			'uid' => $account->uid,
			'new_user' => 0,
		))->execute();  
}

/**
 * Implements hook_user_login().
 */
function user_profile_user_login(&$edit, $account) {
	
	//Unset the existing destination 
	unset($_GET['destination']);
	
	if(is_new_user($account->uid)){
		//Redirect the page to setup the user profile 
		drupal_goto('user-profile');
		
	}else{
		dpm($account);
	
		//Redirect to home page
		drupal_goto('home');
	
	}
}

/*
 * Below function is used to check weather user logged in first time or not?
 *
 */
 function is_new_user($uid){
	
	$is_new_user = db_select('user_profile_master', 'a')
					->fields('a',array('new_user'))
					->condition('uid', $uid)							
					->execute()
					->fetchField();
					
	if($is_new_user == 0) {
		return true;
	}
	return false;
 } 
 